# Generated by Django 6.0 on 2026-01-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikepaar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('usage', models.CharField(max_length=50)),
                ('comfort', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('mileage', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
