# Generated by Django 6.0 on 2026-01-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikepaar', '0006_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikereview',
            name='bike_id',
            field=models.CharField(max_length=150),
        ),
    ]
