# Generated by Django 6.0 on 2026-01-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikepaar', '0009_emailotp_profile_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
