# Generated by Django 6.0.1 on 2026-04-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikepaar', '0010_emailotp_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
