# Generated by Django 6.0.1 on 2026-04-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikepaar', '0011_alter_feedback_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
